### ISSUE TITLE
taps and window.WIN_HAMMING

### ISSUE THREAD

**Issue by cinaeds** [duggabe/gr-control#3]
Hi - it appears  that "window.WIN_HAMMING"  should be "WIN_HAMMING" whien using firdes

**Comment by cinaeds** [comment]
The firdes configuration for the low pass taps

self.low_pass_filter_taps = low_pass_filter_taps = firdes.low_pass(1.6, samp_rate, 4000,1000, window.WIN_HAMMING, 6.76)

should be 

self.low_pass_filter_taps = low_pass_filter_taps = firdes.low_pass(1.6, samp_rate, 4000,1000, WIN_HAMMING, 6.76)

Or "window.WIN_HAMMING" should be "WIN_HAMMING" instead.

**Comment by duggabe** [comment]
There was a change between 3.8 and 3.9 related to this. Which GNU Radio version are you using, and which branch of gr-control did you use?
